name: Build Qt WebEngine

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
        choco install gperf
        choco install winflexbison
        choco install perl
        choco install ninja
        pip install html5lib
        choco install nodejs
        choco install nugetpackagemanager
        NuGet\Install-Package Microsoft.Windows.SDK.CPP.x64 -Version 10.0.26100.3916
    - name: Set up Visual Studio environment
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
    - name: Clone Qt repository
      run: git clone https://code.qt.io/qt/qt5.git
    - name: Checkout version 6.8.3
      run: |
        cd qt5
        git checkout v6.8.3
    - name: Initialize submodules
      run: |
        cd qt5
        .\init-repository.bat
    - name: Create build directory
      run: mkdir qt-build
    - name: Configure Qt
      run: |
        cd qt-build
        ../qt5/configure.bat -prefix %CD%\qt-install -webengine-proprietary-codecs -release -opensource -confirm-license -Wno-dev
    - name: Build Qt
      run: |
        cmake qt5
        cmake --build qt-build --parallel -Wno-dev
    - name: Install Qt
      run: |
        cd qt-build
        cmake --install . -Wno-dev
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qt-webengine
        path: qt-build/qt-install